### ISSUE TITLE
Fees : option to exclude shipping costs from calculation

### ISSUE THREAD

**Issue by CedricAlb** [maciejzgadzaj/commerce_marketplace_paypal#2]
I have basically tested your marketplace_fees branch and it's working good with chained payments. So I merged it to the main branch in my repository and added a feature allowing admin to exclude shipping costs from fee calculation. Don't know if you have this on your roadmap, but wanted to share this : 
https://github.com/CedricAlb/commerce_marketplace_paypal/commit/32f0f6c9168dd1aaa92b548c10e226be54a42ffd

**Comment by maciejzgadzaj** [comment]
Thanks for this Cédric!

Yes, those fees were initially working kinda ok, I didn't feel though they
were properly finished yet (and properly tested). Thanks for helping with
that, I guess I will try to have another look at them over the weekend, and
aim for merging them into the main branch.

Not really convinced to be honest about that excluding shipping cost from
fee calculation, as it feels like kind of an edge case?

And even if so, it should be handled in a bit more generic way - for
example, what about any other custom fee types? Probably it should rather
be based on something like commerce_product_line_item_types() instead? Just
a thought...

M

**Comment by CedricAlb** [comment]
You're right, it's very probable that markeplace's owners could want to filtrate the calculation of their fees to exclude taxes, shipping or others line items... my solution is not very open to other cases. I have to deliver this website quickly (yesterday) but I might re-work this part during my next project.

**Comment by maciejzgadzaj** [comment]
It's always 'for yesterday', isn't it?

Anyway, one thing I have forgotten to mention in my previous comment was that this module actually provides `hook_commerce_marketplace_paypal_wps_adaptive_get_paykey_alter()`, which can be used for altering the Adaptive Payments pay key request before sending it to PayPal (see `commerce_marketplace_paypal_wps_adaptive_get_paykey()`). This way any module could make changes to the receivers/amounts being processed, which should also cover your specific case.

Having this in mind, I think I will not add this feature to the module after all - unless it turns out at one point in the future it is something widely requested.

**Comment by maciejzgadzaj** [comment]
FYI, I have just pushed marketplace fees commit to 7.x-1.x branch here. It seems to work ok now, with correct transactions (with correct amounts) created for each order (so that order balance is 0), though will do some more testing soon, and there might be some minor changes. If you wanna give it a test ride, feel free, any feedback appreciated!
